# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_auto_20170906_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ug',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_one.UserGroup'),
            preserve_default=False,
        ),
    ]
