# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20170908_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='m2m',
            field=models.ManyToManyField(to='app01.Role'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ug',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.UserGroup'),
            preserve_default=False,
        ),
    ]
